<?php

namespace App\Filament\Pages;

use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Illuminate\Contracts\Support\Htmlable;
use ShuvroRoy\FilamentSpatieLaravelHealth\Pages\HealthCheckResults as BaseHealthCheckResults;

class HealthCheckResults extends BaseHealthCheckResults
{
    use HasPageShield;

    protected static ?string $navigationIcon = 'heroicon-o-signal';

    public function getHeading(): string|Htmlable
    {
        return 'Работоспособность';
    }

    public function getTitle(): Htmlable|string
    {
        return 'Работоспособность'; // TODO: Change the autogenerated stub
    }

    public static function getNavigationGroup(): ?string
    {
        return 'Система';
    }
}
